//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBookStoreServiceClient.ABCBookStoreServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/ABCBookStoreService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ISBNNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishingDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorList {
            get {
                return this.AuthorListField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorListField, value) != true)) {
                    this.AuthorListField = value;
                    this.RaisePropertyChanged("AuthorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookTitle {
            get {
                return this.BookTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BookTitleField, value) != true)) {
                    this.BookTitleField = value;
                    this.RaisePropertyChanged("BookTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ISBNNumber {
            get {
                return this.ISBNNumberField;
            }
            set {
                if ((this.ISBNNumberField.Equals(value) != true)) {
                    this.ISBNNumberField = value;
                    this.RaisePropertyChanged("ISBNNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishingDate {
            get {
                return this.PublishingDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishingDateField, value) != true)) {
                    this.PublishingDateField = value;
                    this.RaisePropertyChanged("PublishingDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveBooks", Namespace="http://schemas.datacontract.org/2004/07/ABCBookStoreService")]
    [System.SerializableAttribute()]
    public partial class RetrieveBooks : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet BookSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet BookSet {
            get {
                return this.BookSetField;
            }
            set {
                if ((object.ReferenceEquals(this.BookSetField, value) != true)) {
                    this.BookSetField = value;
                    this.RaisePropertyChanged("BookSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreInsertService")]
    public interface IABCBookStoreInsertService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreInsertService/Insert", ReplyAction="http://tempuri.org/IABCBookStoreInsertService/InsertResponse")]
        string Insert(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreInsertService/Insert", ReplyAction="http://tempuri.org/IABCBookStoreInsertService/InsertResponse")]
        System.Threading.Tasks.Task<string> InsertAsync(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreInsertServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreInsertService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreInsertServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreInsertService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreInsertService {
        
        public ABCBookStoreInsertServiceClient() {
        }
        
        public ABCBookStoreInsertServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreInsertServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreInsertServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreInsertServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book) {
            return base.Channel.Insert(book);
        }
        
        public System.Threading.Tasks.Task<string> InsertAsync(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book) {
            return base.Channel.InsertAsync(book);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreRetrieveByDateService")]
    public interface IABCBookStoreRetrieveByDateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByDateService/RetrieveByDate", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByDateService/RetrieveByDateResponse")]
        ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByDateService/RetrieveByDate", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByDateService/RetrieveByDateResponse")]
        System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByDateAsync(string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreRetrieveByDateServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByDateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreRetrieveByDateServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByDateService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByDateService {
        
        public ABCBookStoreRetrieveByDateServiceClient() {
        }
        
        public ABCBookStoreRetrieveByDateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreRetrieveByDateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByDateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByDateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByDate(string date) {
            return base.Channel.RetrieveByDate(date);
        }
        
        public System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByDateAsync(string date) {
            return base.Channel.RetrieveByDateAsync(date);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreRetrieveByPriceService")]
    public interface IABCBookStoreRetrieveByPriceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByPriceService/RetrieveByPrice", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByPriceService/RetrieveByPriceResponse")]
        ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByPrice(float price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByPriceService/RetrieveByPrice", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByPriceService/RetrieveByPriceResponse")]
        System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByPriceAsync(float price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreRetrieveByPriceServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByPriceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreRetrieveByPriceServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByPriceService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByPriceService {
        
        public ABCBookStoreRetrieveByPriceServiceClient() {
        }
        
        public ABCBookStoreRetrieveByPriceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreRetrieveByPriceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByPriceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByPriceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByPrice(float price) {
            return base.Channel.RetrieveByPrice(price);
        }
        
        public System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByPriceAsync(float price) {
            return base.Channel.RetrieveByPriceAsync(price);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreRetrieveByPublisherService")]
    public interface IABCBookStoreRetrieveByPublisherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByPublisherService/RetrieveByPublisher", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByPublisherService/RetrieveByPublisherRes" +
            "ponse")]
        ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByPublisher(string publisher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByPublisherService/RetrieveByPublisher", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByPublisherService/RetrieveByPublisherRes" +
            "ponse")]
        System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByPublisherAsync(string publisher);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreRetrieveByPublisherServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByPublisherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreRetrieveByPublisherServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByPublisherService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByPublisherService {
        
        public ABCBookStoreRetrieveByPublisherServiceClient() {
        }
        
        public ABCBookStoreRetrieveByPublisherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreRetrieveByPublisherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByPublisherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByPublisherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByPublisher(string publisher) {
            return base.Channel.RetrieveByPublisher(publisher);
        }
        
        public System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByPublisherAsync(string publisher) {
            return base.Channel.RetrieveByPublisherAsync(publisher);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreRetrieveByAuthorService")]
    public interface IABCBookStoreRetrieveByAuthorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByAuthorService/RetrieveByAuthor", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByAuthorService/RetrieveByAuthorResponse")]
        ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByAuthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveByAuthorService/RetrieveByAuthor", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveByAuthorService/RetrieveByAuthorResponse")]
        System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByAuthorAsync(string author);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreRetrieveByAuthorServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByAuthorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreRetrieveByAuthorServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByAuthorService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveByAuthorService {
        
        public ABCBookStoreRetrieveByAuthorServiceClient() {
        }
        
        public ABCBookStoreRetrieveByAuthorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreRetrieveByAuthorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByAuthorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveByAuthorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveByAuthor(string author) {
            return base.Channel.RetrieveByAuthor(author);
        }
        
        public System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveByAuthorAsync(string author) {
            return base.Channel.RetrieveByAuthorAsync(author);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreDeleteService")]
    public interface IABCBookStoreDeleteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreDeleteService/Delete", ReplyAction="http://tempuri.org/IABCBookStoreDeleteService/DeleteResponse")]
        string Delete(float isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreDeleteService/Delete", ReplyAction="http://tempuri.org/IABCBookStoreDeleteService/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(float isbn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreDeleteServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreDeleteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreDeleteServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreDeleteService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreDeleteService {
        
        public ABCBookStoreDeleteServiceClient() {
        }
        
        public ABCBookStoreDeleteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreDeleteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreDeleteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreDeleteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Delete(float isbn) {
            return base.Channel.Delete(isbn);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(float isbn) {
            return base.Channel.DeleteAsync(isbn);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreUpdateService")]
    public interface IABCBookStoreUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreUpdateService/Update", ReplyAction="http://tempuri.org/IABCBookStoreUpdateService/UpdateResponse")]
        string Update(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreUpdateService/Update", ReplyAction="http://tempuri.org/IABCBookStoreUpdateService/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreUpdateServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreUpdateServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreUpdateService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreUpdateService {
        
        public ABCBookStoreUpdateServiceClient() {
        }
        
        public ABCBookStoreUpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreUpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreUpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Update(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book) {
            return base.Channel.Update(book);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(ABCBookStoreServiceClient.ABCBookStoreServiceReference.Book book) {
            return base.Channel.UpdateAsync(book);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABCBookStoreServiceReference.IABCBookStoreRetrieveAllService")]
    public interface IABCBookStoreRetrieveAllService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveAllService/RetrieveAll", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveAllService/RetrieveAllResponse")]
        ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABCBookStoreRetrieveAllService/RetrieveAll", ReplyAction="http://tempuri.org/IABCBookStoreRetrieveAllService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABCBookStoreRetrieveAllServiceChannel : ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveAllService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABCBookStoreRetrieveAllServiceClient : System.ServiceModel.ClientBase<ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveAllService>, ABCBookStoreServiceClient.ABCBookStoreServiceReference.IABCBookStoreRetrieveAllService {
        
        public ABCBookStoreRetrieveAllServiceClient() {
        }
        
        public ABCBookStoreRetrieveAllServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABCBookStoreRetrieveAllServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveAllServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABCBookStoreRetrieveAllServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks RetrieveAll() {
            return base.Channel.RetrieveAll();
        }
        
        public System.Threading.Tasks.Task<ABCBookStoreServiceClient.ABCBookStoreServiceReference.RetrieveBooks> RetrieveAllAsync() {
            return base.Channel.RetrieveAllAsync();
        }
    }
}
